# Generated by Django 4.2.13 on 2024-10-21 20:29

from django.db import migrations, models
import employeeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(validators=[employeeapp.models.validate_age])),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
